const baseVariables = {
  // Typography Scale
  "--text-xs": "0.75rem",
  "--text-sm": "0.875rem",
  "--text-base": "1rem",
  "--text-lg": "1.125rem",
  "--text-xl": "1.25rem",
  "--text-2xl": "1.5rem",
  "--text-3xl": "1.875rem",
  "--text-4xl": "2.25rem",
  "--text-5xl": "3rem",
  "--text-6xl": "3.75rem",

  // Font Weights
  "--font-thin": "100",
  "--font-extralight": "200",
  "--font-light": "300",
  "--font-regular": "400",
  "--font-medium": "500",
  "--font-semibold": "600",
  "--font-bold": "700",
  "--font-extrabold": "800",
  "--font-black": "900",

  // Spacing Scale
  "--spacing-xs": "0.25rem",
  "--spacing-sm": "0.5rem",
  "--spacing-md": "1rem",
  "--spacing-lg": "1.5rem",
  "--spacing-xl": "2rem",
  "--spacing-2xl": "3rem",

  // Z-Indices
  "--z-base": "0",
  "--z-elevated": "10",
  "--z-header": "40",
  "--z-dropdown": "50",
  "--z-modal": "100",
  "--z-tooltip": "200",

  // Motion
  "--duration-fast": "150ms",
  "--duration-normal": "250ms",
  "--duration-slow": "350ms",
  "--ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--ease-out": "cubic-bezier(0.0, 0, 0.2, 1)",
  "--ease-in": "cubic-bezier(0.4, 0, 1, 1)",

  // Border Radius
  "--radius-pill": "9999px",
  "--radius-full": "50%",

  // Outline
  "--outline-width": "2px",
  "--outline-offset": "2px",

  // Overlay
  "--overlay-opacity": "0.5",

  // Common Sizes
  "--size-icon-sm": "20px",
  "--size-icon-md": "24px",
  "--size-icon-lg": "32px",
  "--size-touch-target": "44px",

  // Shadows (consistent relative to theme colors)
  "--shadow-sm": "2px 2px 0px 0px var(--card-border)",
  "--shadow-sm-hover": "3px 3px 0px 0px var(--card-border)",
  "--shadow-sm-checked": "3px 3px 0px 0px var(--card-border)",
  "--shadow-sm-checked-hover": "4px 4px 0px 0px var(--card-border)",
  "--shadow-lg": "8px 8px 0px 0px var(--card-border)",
};

export const themes = {
  default: {
    name: "Default",
    variables: {
      ...baseVariables,
      "--background": "#e0e7ff",
      "--foreground": "#000000",
      "--card-bg": "#ffffff",
      "--card-border": "#000000",
      "--primary": "#a855f7",
      "--primary-hover": "#9333ea",
      "--primary-foreground": "#000000",
      "--shadow-primary": "#7e22ce",
      "--secondary": "#fbbf24",
      "--secondary-foreground": "#000000",
      "--accent": "#ec4899",
      "--muted": "#94a3b8",
      "--muted-foreground": "#334155",
      "--success": "#22c55e",
      "--success-foreground": "#000000",
      "--warning": "#f59e0b",
      "--warning-foreground": "#000000",
      "--error": "#ef4444",
      "--error-foreground": "#000000",
      "--shadow-error": "#b91c1c",
      "--border-width": "3px",
      "--radius": "8px",
      "--shadow-hard": "5px 5px 0px 0px #000000",
      "--shadow-hover": "7px 7px 0px 0px #000000",
      "--font-heading": "var(--font-montserrat)",
      "--heading-transform": "uppercase",
      "--heading-weight": "900",
    },
  },
  doom: {
    name: "DOOMSDAY",
    variables: {
      ...baseVariables,
      "--background": "#020617",
      "--foreground": "#e2e8f0",
      "--card-bg": "#0f172a",
      "--card-border": "#1e293b",
      "--primary": "#10b981",
      "--primary-hover": "#059669",
      "--primary-foreground": "#020617",
      "--shadow-primary": "#000000",
      "--secondary": "#334155",
      "--secondary-foreground": "#f8fafc",
      "--accent": "#fbbf24",
      "--muted": "#64748b",
      "--muted-foreground": "#94a3b8",
      "--success": "#10b981",
      "--success-foreground": "#020617",
      "--warning": "#fbbf24",
      "--warning-foreground": "#020617",
      "--error": "#ef4444",
      "--error-foreground": "#000000",
      "--shadow-error": "#000000",
      "--border-width": "2px",
      "--radius": "2px",
      "--shadow-hard": "5px 5px 0px 0px #000000",
      "--shadow-hover": "7px 7px 0px 0px #000000",
      "--font-heading": "var(--font-montserrat)",
      "--heading-transform": "uppercase",
      "--heading-weight": "700",
    },
  },
  neighbor: {
    name: "THE CAPTAIN",
    variables: {
      ...baseVariables,
      "--background": "#F8FAFC",
      "--foreground": "#0F172A",
      "--card-bg": "#FFFFFF",
      "--card-border": "#002D72",
      "--primary": "#002D72",
      "--primary-hover": "#1E3A8A",
      "--primary-foreground": "#FFFFFF",
      "--shadow-primary": "#001533",
      "--secondary": "#B91C1C",
      "--secondary-foreground": "#FFFFFF",
      "--accent": "#C0C0C0",
      "--muted": "#64748B",
      "--muted-foreground": "#475569",
      "--success": "#15803D",
      "--success-foreground": "#FFFFFF",
      "--warning": "#B45309",
      "--warning-foreground": "#FFFFFF",
      "--error": "#B91C1C",
      "--error-foreground": "#FFFFFF",
      "--shadow-error": "#7f1d1d",
      "--border-width": "3px",
      "--radius": "8px",
      "--shadow-hard": "6px 6px 0px 0px #0F172A",
      "--shadow-hover": "8px 8px 0px 0px #0F172A",
      "--font-heading": "var(--font-montserrat)",
      "--heading-transform": "uppercase",
      "--heading-weight": "900",
    },
  },
  vigilante: {
    name: "DARK KNIGHT",
    variables: {
      ...baseVariables,
      "--background": "#0F1419",
      "--foreground": "#E8E9ED",
      "--card-bg": "#1A1F29",
      "--card-border": "#2D3748",
      "--primary": "#F7B731",
      "--primary-hover": "#F5A623",
      "--primary-foreground": "#0F1419",
      "--shadow-primary": "#000000",
      "--secondary": "#4A5568",
      "--secondary-foreground": "#E8E9ED",
      "--accent": "#3B82F6",
      "--muted": "#718096",
      "--muted-foreground": "#A0AEC0",
      "--success": "#48BB78",
      "--success-foreground": "#0F1419",
      "--warning": "#ED8936",
      "--warning-foreground": "#0F1419",
      "--error": "#F56565",
      "--error-foreground": "#000000",
      "--shadow-error": "#000000",
      "--border-width": "2px",
      "--radius": "6px",
      "--shadow-hard": "5px 5px 0px 0px #000000",
      "--shadow-hover": "7px 7px 0px 0px #000000",
      "--font-heading": "var(--font-montserrat)",
      "--heading-transform": "uppercase",
      "--heading-weight": "700",
    },
  },
} as const;

export type ThemeKey = keyof typeof themes;
