import { baseVariables, palette } from "../tokens";
import { createSolidTokens } from "./solid-tokens";

export const themes = {
  default: {
    name: "Default",
    variables: {
      ...baseVariables,
      "--accent": palette.red[500],
      "--background": palette.indigo[100],
      "--border-strong": palette.black[950],
      "--card-bg": palette.white[950],
      "--card-border": palette.black[950],
      "--error": palette.red[500],
      "--error-foreground": palette.black[950],
      "--foreground": palette.black[950],
      "--muted": palette.gray[400],
      "--muted-foreground": palette.gray[700],
      "--on-surface": palette.black[950],
      "--on-surface-muted": palette.gray[700],
      "--primary": palette.purple[500],
      "--primary-foreground": palette.black[950],
      "--surface-brand": palette.purple[500],
      "--surface-brand-foreground": palette.black[950],
      "--primary-hover": palette.purple[600],
      "--secondary": palette.yellow[400],
      "--secondary-foreground": palette.black[950],
      "--shadow-base": palette.black[950],
      "--shadow-error": palette.red[800],
      "--shadow-primary": palette.purple[800],
      "--success": palette.green[500],
      "--success-foreground": palette.black[950],
      "--surface-accent": palette.slate[100],
      "--warning": palette.yellow[500],
      "--warning-foreground": palette.black[950],
    },
    solid: createSolidTokens(palette.purple[500], palette.black[900], {
      success: palette.green[500],
      error: palette.red[500],
      warning: palette.yellow[500],
    }),
  },
  doom: {
    name: "DOOMSDAY",
    variables: {
      ...baseVariables,
      "--accent": palette.red[500],
      "--background": palette.slate[950],
      "--border-strong": palette.slate[700],
      "--card-bg": palette.slate[900],
      "--card-border": palette.slate[800],
      "--error": palette.red[500],
      "--error-foreground": palette.black[950],
      "--foreground": palette.slate[200],
      "--muted": palette.slate[500],
      "--muted-foreground": palette.slate[400],
      "--on-surface": palette.slate[200],
      "--on-surface-muted": palette.slate[400],
      "--primary": palette.green[600],
      "--primary-foreground": palette.slate[950],
      "--surface-brand": palette.green[600],
      "--surface-brand-foreground": palette.slate[950],
      "--primary-hover": palette.green[700],
      "--secondary": palette.slate[600],
      "--secondary-foreground": palette.slate[50],
      "--shadow-base": palette.black[950],
      "--shadow-error": palette.red[800],
      "--shadow-primary": palette.green[900],
      "--success": palette.green[600],
      "--success-foreground": palette.slate[950],
      "--surface-accent": palette.slate[900],
      "--warning": palette.yellow[500],
      "--warning-foreground": palette.slate[950],
    },
    solid: createSolidTokens(palette.green[600], palette.black[950], {
      success: palette.green[600],
      error: palette.red[500],
      warning: palette.yellow[500],
    }),
  },
  captain: {
    name: "THE CAPTAIN",
    variables: {
      ...baseVariables,
      "--accent": palette.red[600],
      "--background": palette.slate[50],
      "--border-strong": palette.slate[900],
      "--card-bg": palette.white[950],
      "--card-border": palette.black[950],
      "--error": palette.red[600],
      "--error-foreground": palette.white[950],
      "--foreground": palette.slate[900],
      "--muted": palette.slate[400],
      "--muted-foreground": palette.slate[600],
      "--on-surface": palette.slate[900],
      "--on-surface-muted": palette.slate[600],
      "--primary": palette.blue[500],
      "--primary-foreground": palette.black[950],
      "--surface-brand": palette.blue[500],
      "--surface-brand-foreground": palette.black[950],
      "--primary-hover": palette.blue[600],
      "--secondary": palette.slate[500],
      "--secondary-foreground": palette.white[950],
      "--shadow-base": palette.black[950],
      "--shadow-error": palette.red[900],
      "--shadow-primary": palette.blue[800],
      "--success": palette.green[600],
      "--success-foreground": palette.black[950],
      "--surface-accent": palette.slate[100],
      "--warning": palette.yellow[600],
      "--warning-foreground": palette.gray[950],
    },
    solid: createSolidTokens(palette.blue[500], palette.black[950], {
      success: palette.green[600],
      error: palette.red[600],
      warning: palette.yellow[600],
    }),
  },
  vigilante: {
    name: "DARK KNIGHT",
    variables: {
      ...baseVariables,
      "--accent": palette.blue[500],
      "--background": palette.gray[950],
      "--border-strong": palette.gray[900],
      "--card-bg": palette.gray[975],
      "--card-border": palette.gray[990],
      "--error": palette.red[700],
      "--error-foreground": palette.black[950],
      "--foreground": "#E8E9ED",
      "--muted": palette.gray[500],
      "--muted-foreground": palette.gray[400],
      "--on-surface": "#E8E9ED",
      "--on-surface-muted": palette.gray[400],
      "--primary": palette.yellow[600],
      "--primary-foreground": palette.gray[950],
      "--surface-brand": palette.yellow[600],
      "--surface-brand-foreground": palette.gray[950],
      "--primary-hover": palette.yellow[700],
      "--secondary": palette.gray[600],
      "--secondary-foreground": "#E8E9ED",
      "--shadow-base": palette.black[950],
      "--shadow-error": palette.red[900],
      "--shadow-primary": palette.yellow[900],
      "--success": palette.green[400],
      "--success-foreground": palette.gray[950],
      "--surface-accent": palette.gray[900],
      "--warning": palette.yellow[700],
      "--warning-foreground": palette.gray[950],
    },
    solid: createSolidTokens(palette.yellow[600], palette.gray[950], {
      success: palette.green[400],
      error: palette.red[700],
      warning: palette.yellow[700],
    }),
  },
} as const;

export type ThemeKey = keyof typeof themes;
