import { palette, baseVariables } from "../tokens";

export const themes = {
  default: {
    name: "Default",
    variables: {
      ...baseVariables,
      "--background": palette.gray[100],
      "--foreground": palette.common.black,
      "--card-bg": palette.common.white,
      "--card-border": palette.common.black,
      "--surface-accent": palette.blue[100],
      "--primary": palette.purple[500],
      "--primary-hover": palette.purple[600],
      "--primary-foreground": palette.common.black,
      "--shadow-primary": palette.purple[700],
      "--secondary": palette.yellow[400],
      "--secondary-foreground": palette.common.black,
      "--accent": palette.red[500],
      "--muted": palette.gray[400],
      "--muted-foreground": palette.gray[700],
      "--success": palette.green[500],
      "--success-foreground": palette.common.black,
      "--warning": palette.yellow[500],
      "--warning-foreground": palette.common.black,
      "--error": palette.red[500],
      "--error-foreground": palette.common.black,
      "--on-surface": palette.common.black,
      "--on-surface-muted": palette.gray[700],
      "--shadow-error": palette.red[600],
    },
  },
  doom: {
    name: "DOOMSDAY",
    variables: {
      ...baseVariables,
      "--background": palette.slate[950],
      "--foreground": palette.slate[200],
      "--card-bg": palette.slate[900],
      "--card-border": palette.slate[800],
      "--surface-accent": palette.slate[900],
      "--primary": palette.green[600],
      "--primary-hover": palette.green[700],
      "--primary-foreground": palette.slate[950],
      "--shadow-primary": palette.common.black,
      "--secondary": palette.slate[700],
      "--secondary-foreground": palette.slate[50],
      "--accent": palette.yellow[400],
      "--muted": palette.slate[500],
      "--muted-foreground": palette.slate[400],
      "--success": palette.green[600],
      "--success-foreground": palette.slate[950],
      "--warning": palette.yellow[400],
      "--warning-foreground": palette.slate[950],
      "--error": palette.red[500],
      "--error-foreground": palette.common.black,
      "--on-surface": palette.slate[200],
      "--on-surface-muted": palette.slate[400],
      "--shadow-error": palette.common.black,
    },
  },
  neighbor: {
    name: "THE CAPTAIN",
    variables: {
      ...baseVariables,
      "--background": palette.slate[50],
      "--foreground": palette.slate[900],
      "--card-bg": palette.common.white,
      "--card-border": palette.common.black,
      "--surface-accent": palette.slate[100],
      "--primary": palette.blue[600],
      "--primary-hover": palette.blue[700],
      "--primary-foreground": palette.common.white,
      "--shadow-primary": palette.blue[800],
      "--secondary": palette.slate[500],
      "--secondary-foreground": palette.common.white,
      "--accent": palette.red[600],
      "--muted": palette.slate[400],
      "--muted-foreground": palette.slate[600],
      "--success": palette.green[600],
      "--success-foreground": palette.common.white,
      "--warning": palette.yellow[600],
      "--warning-foreground": palette.gray[950],
      "--error": palette.red[600],
      "--error-foreground": palette.common.white,
      "--on-surface": palette.slate[900],
      "--on-surface-muted": palette.slate[600],
      "--shadow-error": palette.red[800],
      "--border-strong": palette.slate[900],
    },
  },
  vigilante: {
    name: "DARK KNIGHT",
    variables: {
      ...baseVariables,
      "--background": palette.gray[950],
      "--foreground": "#E8E9ED",
      "--card-bg": palette.gray[975],
      "--card-border": palette.gray[990],
      "--surface-accent": palette.gray[900],
      "--primary": palette.yellow[600],
      "--primary-hover": palette.yellow[700],
      "--primary-foreground": palette.gray[950],
      "--shadow-primary": palette.common.black,
      "--secondary": palette.gray[600],
      "--secondary-foreground": "#E8E9ED",
      "--accent": palette.blue[500],
      "--muted": palette.gray[500],
      "--muted-foreground": palette.gray[400],
      "--success": palette.green[400],
      "--success-foreground": palette.gray[950],
      "--warning": palette.yellow[700],
      "--warning-foreground": palette.gray[950],
      "--error": palette.red[700],
      "--error-foreground": palette.common.black,
      "--on-surface": "#E8E9ED",
      "--on-surface-muted": palette.gray[400],
      "--shadow-error": palette.common.black,
    },
  },
} as const;

export type ThemeKey = keyof typeof themes;
